export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";
export const SET_USER_PROFILE = "SET_USER_PROFILE";
export const WITHDRAW_MONEY = "WITHDRAW_MONEY";
export const DEPOSIT_MONEY = "DEPOSIT_MONEY";